# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: splitlearning.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'splitlearning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13splitlearning.proto\x12\rsplitlearning\"=\n\x12\x41\x63tivationsRequest\x12\x13\n\x0b\x61\x63tivations\x18\x01 \x03(\x02\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"*\n\x13\x41\x63tivationsResponse\x12\x13\n\x0b\x61\x63tivations\x18\x01 \x03(\x02\"9\n\x10GradientsRequest\x12\x11\n\tgradients\x18\x01 \x03(\x02\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"&\n\x11GradientsResponse\x12\x11\n\tgradients\x18\x01 \x03(\x02\x32\xbb\x01\n\rSplitLearning\x12W\n\x0eSendActivation\x12!.splitlearning.ActivationsRequest\x1a\".splitlearning.ActivationsResponse\x12Q\n\x0cSendGradient\x12\x1f.splitlearning.GradientsRequest\x1a .splitlearning.GradientsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splitlearning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVATIONSREQUEST']._serialized_start=38
  _globals['_ACTIVATIONSREQUEST']._serialized_end=99
  _globals['_ACTIVATIONSRESPONSE']._serialized_start=101
  _globals['_ACTIVATIONSRESPONSE']._serialized_end=143
  _globals['_GRADIENTSREQUEST']._serialized_start=145
  _globals['_GRADIENTSREQUEST']._serialized_end=202
  _globals['_GRADIENTSRESPONSE']._serialized_start=204
  _globals['_GRADIENTSRESPONSE']._serialized_end=242
  _globals['_SPLITLEARNING']._serialized_start=245
  _globals['_SPLITLEARNING']._serialized_end=432
# @@protoc_insertion_point(module_scope)
