# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: siamese.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'siamese.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsiamese.proto\x12\x07siamese\"s\n\x0e\x43lientToServer\x12\x14\n\x0c\x61\x63tivations1\x18\x01 \x03(\x02\x12\x14\n\x0c\x61\x63tivations2\x18\x02 \x03(\x02\x12\x0e\n\x06labels\x18\x03 \x03(\x05\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\x12\x11\n\tclient_id\x18\x05 \x01(\x05\"F\n\x0eServerToClient\x12\x12\n\ngradients1\x18\x01 \x03(\x02\x12\x12\n\ngradients2\x18\x02 \x03(\x02\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x32V\n\x07Siamese\x12K\n\x15SendClientActivations\x12\x17.siamese.ClientToServer\x1a\x17.siamese.ServerToClient\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'siamese_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTTOSERVER']._serialized_start=26
  _globals['_CLIENTTOSERVER']._serialized_end=141
  _globals['_SERVERTOCLIENT']._serialized_start=143
  _globals['_SERVERTOCLIENT']._serialized_end=213
  _globals['_SIAMESE']._serialized_start=215
  _globals['_SIAMESE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
